<?php

/**
 * @file
 * Hook implementations for commerce_payu_webcheckout_siembraco.
 */

use Drupal\commerce_payu_webcheckout_siembraco\EntityOperations;
use Drupal\commerce_order\Entity\OrderInterface;
use Drupal\commerce_payment\Entity\PaymentGatewayInterface;

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function commerce_payu_webcheckout_siembraco_commerce_order_delete(OrderInterface $order) {
  Drupal::service('class_resolver')
    ->getInstanceFromDefinition(EntityOperations::class)
    ->onOrderDelete($order);
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function commerce_payu_webcheckout_siembraco_commerce_payment_gateway_delete(PaymentGatewayInterface $gateway) {
  Drupal::service('class_resolver')
    ->getInstanceFromDefinition(EntityOperations::class)
    ->onGatewayDelete($gateway);
}
